### ISSUE TITLE
make database schema in MySQL

### ISSUE THREAD

**Issue by riera90** [riera90/pw#6]

**Comment by spookynel** [comment]
To solve/check:
#### User table:
- id (PK):	 is set to INT type autoincrement.
- interests: is set to VARCHAR type despite being a foreign key to Topic(id). For that reason, a foreign key constraint cannot be made.

#### Post:
- id (PK):	 is set to INT type autoincrement.
- All date atributes are DATETIME type.
- states: is set to ENUM type
- type: is set to ENUM type
- sentTo: is set to VARCHAR type despite being a foreign key to User(id). For that reason, a foreign key constraint cannot be made.
- topics: is set to VARCHAR type despite being a foreign key to Topic(id). For that reason, a foreign key constraint cannot be made.

**Comment by riera90** [comment]
# User
- [x] id
- [ ] The interests need a second table to be able to be represented in sql

# Post
- [x] id
- [x] All datetime
- [x] states
- [x] type
- [ ] sentTo: same as the interests in the User table
- [ ] topics: same as interests in User table

If I remember correctly, when you create the database in MyAdminer you can export the table creation script, upload it to the branch you are working on.

If you can export the data created in the adminer, do the same as for the tables script.
